"""Provenance and citation validation module.

Enforces that every number or scientific claim presented to users
or generated by agents maps to a verified dataset ID and official source URL.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime, timezone

try:
    from pydantic import BaseModel, Field
    HAS_PYDANTIC = True
except ImportError:
    HAS_PYDANTIC = False

if HAS_PYDANTIC:
    class ProvenanceRecord(BaseModel):
        """Standardized metadata block attached to telemetry figures and risk scores."""
        dataset_id: str = Field(..., description="Unique dataset accession, e.g. NASA-OSD-575, NASA-STD-3001")
        source_url: str = Field(..., description="Canonical source URL for scientific verification")
        data_mode: str = Field(default="live", description="Data provenance mode: 'live', 'cache', or 'fixture'")
        timestamp_utc: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
        raw_tool_json: Optional[Dict[str, Any]] = Field(default=None, description="Raw tool execution parameters and outputs")

    class NumericClaim(BaseModel):
        """Single numeric or factual claim to be validated before user presentation."""
        text: str
        source_url: str
        dataset_id: str
        numeric_value: Optional[float] = None
        unit: Optional[str] = None
else:
    class ProvenanceRecord:
        def __init__(self, dataset_id: str, source_url: str, data_mode: str = "live", timestamp_utc: Optional[str] = None, raw_tool_json: Optional[Dict[str, Any]] = None):
            self.dataset_id = dataset_id
            self.source_url = source_url
            self.data_mode = data_mode
            self.timestamp_utc = timestamp_utc or datetime.now(timezone.utc).isoformat()
            self.raw_tool_json = raw_tool_json

        def model_dump(self) -> Dict[str, Any]:
            return {
                "dataset_id": self.dataset_id,
                "source_url": self.source_url,
                "data_mode": self.data_mode,
                "timestamp_utc": self.timestamp_utc,
                "raw_tool_json": self.raw_tool_json,
            }


def cite_check(claims: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Validate that every numeric or observational claim carries a valid source URL and dataset ID.

    Blocks output if any claim is ungrounded or missing citation credentials.
    """
    if not claims:
        return {
            "valid": True,
            "total_claims": 0,
            "passed_count": 0,
            "failed_claims": [],
            "status": "PASS_EMPTY",
        }

    failed = []
    passed = 0

    for c in claims:
        text = str(c.get("text", "")).strip()
        url = str(c.get("source_url", "")).strip()
        ds_id = str(c.get("dataset_id", "")).strip()

        # Check existence and basic validity
        has_url = bool(url.startswith("http://") or url.startswith("https://"))
        has_id = bool(len(ds_id) >= 3)
        has_text = bool(len(text) > 0)

        if has_text and has_url and has_id:
            passed += 1
        else:
            failed.append({
                "claim": text,
                "missing": [
                    k for k, v in [("text", has_text), ("source_url", has_url), ("dataset_id", has_id)] if not v
                ],
            })

    is_valid = len(failed) == 0
    return {
        "valid": is_valid,
        "total_claims": len(claims),
        "passed_count": passed,
        "failed_claims": failed,
        "status": "PASS" if is_valid else "BLOCKED_UNGROUNDED_CLAIMS",
    }


def attach_provenance(
    payload: Dict[str, Any],
    dataset_id: str,
    source_url: str,
    data_mode: str = "live",
    raw_tool_json: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Helper to attach standardized provenance block to API response dictionaries."""
    out = dict(payload)
    out["provenance"] = ProvenanceRecord(
        dataset_id=dataset_id,
        source_url=source_url,
        data_mode=data_mode,
        timestamp_utc=datetime.now(timezone.utc).isoformat(),
        raw_tool_json=raw_tool_json or {},
    ).model_dump()
    return out
