import os
import re
from pathlib import Path

# Working docs and directories that are ignored or internal
IGNORED_DIRS = {
    "node_modules", "venv", ".venv", "dist", ".git", "__pycache__",
    ".idea", ".vscode", ".vite", "osdr_i4"
}

IGNORED_FILES = {
    "HANDOFF.md", "AGENT_HANDOFF.md", "MASTER_PROMPT.md",
    "astrovitals.db", "package-lock.json", "verify_sanitization.py"
}

# Search terms: AI tool credits / models
SUSPICIOUS_PATTERNS = [
    r"TanvirAdmin@2026",
    r"\bantigravity\b",
    r"\bclaude\b",
    r"\bchatgpt\b",
    r"\bgpt-4\b",
    r"\bgpt-3\b",
    r"ai-generated",
    r"made with ai",
    r"generated by ai",
    r"courtesy of claude",
    r"prompted by",
]

def scan_files():
    root = Path(".")
    violations = []
    
    for path in root.rglob("*"):
        # Check ignored dirs
        if any(ignored in path.parts for ignored in IGNORED_DIRS):
            continue
        if path.name in IGNORED_FILES or path.name.endswith(".backup.md") or path.suffix in [".pyc", ".db", ".png", ".jpg", ".webp", ".ico"]:
            continue
        if not path.is_file():
            continue
            
        try:
            content = path.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
            
        for pat in SUSPICIOUS_PATTERNS:
            matches = re.finditer(pat, content, re.IGNORECASE)
            for m in matches:
                # Exclude legitimate Gemini API SDK mentions in code (e.g. google.genai, GEMINI_API_KEY)
                line_no = content[:m.start()].count("\n") + 1
                line = content.splitlines()[line_no - 1].strip() if line_no <= len(content.splitlines()) else ""
                violations.append((str(path), line_no, m.group(0), line))
                
    return violations

if __name__ == "__main__":
    v = scan_files()
    if not v:
        print("ALL COMMITTED FILES CLEAN: 0 suspicious AI tool credits or hardcoded secrets found!")
    else:
        print(f"FOUND {len(v)} POTENTIAL MATCHES:")
        for path, line_no, term, line in v:
            print(f"  {path}:{line_no} [{term}] -> {line[:80]}")
